apiVersion: flink.k8s.io/v1alpha1
kind: FlinkApplication
metadata:
  name: flink-example-statemachine
spec:
  imageName: apache/flink:1.14.2
  jarURI: local:///opt/flink/artifacts/myjob.jar
  entryClass: org.apache.flink.streaming.examples.statemachine.StateMachineExample
  parallelism: 2
  jobManagerResource:
    mem: 1024m
    cpu: 0.5
  taskManagerResource:
    mem: 1024m
    cpu: 0.5
  flinkConfig:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.service-account: flink
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: file:///opt/flink/volume/flink-ha
    state.checkpoints.dir: file:///opt/flink/volume/flink-cp
    state.savepoints.dir: file:///opt/flink/volume/flink-sp
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: jobmanager-pod-template
    spec:
      initContainers:
        - name: artifacts-fetcher
          image: busybox:latest
          # Use wget or other tools to get user jars from remote storage
          command: [ 'wget', 'https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.14.3/flink-examples-streaming_2.12-1.14.3.jar', '-O', '/flink-artifact/myjob.jar' ]
          volumeMounts:
            - mountPath: /flink-artifact
              name: flink-artifact
      containers:
        # Do not change the main container name
        - name: flink-main-container
          resources:
            requests:
              ephemeral-storage: 2048Mi
            limits:
              ephemeral-storage: 2048Mi
          volumeMounts:
            - mountPath: /opt/flink/artifacts
              name: flink-artifact
            - mountPath: /opt/flink/volume
              name: flink-volume
      volumes:
        - name: flink-artifact
          emptyDir: { }
        - name: flink-volume
          persistentVolumeClaim:
            claimName: flink-example-statemachine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-example-statemachine
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
