apiVersion: flink.k8s.io/v1alpha1
kind: FlinkApplication
metadata:
  name: flink-example-statemachine
spec:
  imageName: apache/flink:1.14.2
  jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
  parallelism: 2
  jobManagerResource:
    mem: 1024m
    cpu: 0.5
  taskManagerResource:
    mem: 1024m
    cpu: 0.5
  savepointsDir: file:///tmp/savepoints
  savepointGeneration: 0
  flinkConfig:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.jobmanager.service-account: flink