apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flinkapplications.flink.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: flink.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                imageName:
                  type: string
                jarURI:
                  type: string
                entryClass:
                  type: string
                parallelism:
                  type: integer
                jobManagerResource:
                  type: object
                  properties:
                    mem:
                      type: string
                    cpu:
                      type: number
                taskManagerResource:
                  type: object
                  properties:
                    mem:
                      type: string
                    cpu:
                      type: number
                flinkConfig:
                  type: object
                  additionalProperties:
                    type: string
                podTemplate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: FlinkApplication
    plural: flinkapplications
    singular: flinkapplication
    shortNames:
      - flinkapp
  scope: Namespaced
