apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
subjects:
- kind: ServiceAccount
  name: flink
  namespace: default
roleRef:
  kind: Role
  name: flink
  apiGroup: rbac.authorization.k8s.io
